Add back 3.7 support
eventlet/eventlet pull request #848
Opened 2023-12-18 17:36 UTC by itamarst

Fixes #846 

1. Add back 3.7 support
2. Make 3.7 tests pass. I'm ... a little worried about this part but I did try to limit it so it mostly just impacts 3.7, except in one case where it was eventlet being incompatible with documented stdlib API.

2023-12-18 17:37 UTC, itamarst commented on eventlet/green/ssl.py
> +                    elif _is_py_3_7 and "unexpected eof" in exc.args[1]:
The error code is `1` in this case, which is Not Helpful.

2023-12-18 17:37 UTC, itamarst commented on tox.ini
> +    coverage
Just use whichever version works with current Python version.

2023-12-19 11:14 UTC, 4383 requested changes
Please also remove https://github.com/eventlet/eventlet/blob/master/NEWS#L4

2023-12-19 11:38 UTC, 4383 approved these changes
Changelog updated here https://github.com/eventlet/eventlet/pull/849

2023-12-19 11:39 UTC, merged