Supporting Python 3.13
eventlet/eventlet pull request #966
Opened 2024-06-10 14:41 UTC by 4383

Supporting Python 3.13 as it will become soon a reality https://devguide.python.org/versions/

2024-06-11 12:28 UTC, itamarst commented
Note that for prereleases you need to be more specific in GitHub Actions, you can't just say "3.13" until 3.13 is actually out.

2024-06-11 12:32 UTC, 4383 commented
Indeed the beta suffix seems the right way to do that, kudos

2024-06-11 12:33 UTC, itamarst commented
It looks like 3.13 beta2 has only partially made it through the GitHub Actions support process; they did first part yesterday, so might become available today. So at minimum need to wait for that and rerun tests. 

It's unclear to me why macOS is failing with a different kind of error.

2024-06-11 12:34 UTC, itamarst requested changes
Need to reach state where tests can actually run, blocked on GitHub Actions (no point in running on old beta).

2024-06-11 12:36 UTC, 4383 commented
version": "3.13.0-beta.1" seems the last version available for Python 3.13

2024-06-11 12:37 UTC, 4383 commented
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

2024-06-11 12:39 UTC, 4383 commented
> It looks like 3.13 beta2 has only partially made it through the GitHub Actions support process; they did first part yesterday, so might become available today. So at minimum need to wait for that and rerun tests.

No rush we can pause it during a couple of day. Python 3.13 will be officially released in October.

2024-06-11 12:43 UTC, 4383 commented
Concerning macOS, I think we have to use `darwin` rather than `macOS-latest`.

2024-06-17 13:11 UTC, itamarst commented
Progress, of sorts. `greenlet` package doesn't work on 3.13, so that's a blocker.

2024-06-17 13:12 UTC, itamarst commented
We can track progress here: https://github.com/python-greenlet/greenlet/pull/396

2024-06-17 14:11 UTC, 4383 commented
> Progress, of sorts. `greenlet` package doesn't work on 3.13, so that's a blocker.

That's a concerning problem, and far from our responsibility though...

2024-06-17 17:38 UTC, itamarst commented
It's being worked on, at least, so seems OK.

2024-09-11 12:10 UTC, itamarst commented
Looks like greenlet now supports 3.13.

2024-09-11 12:35 UTC, itamarst commented
Some 3.13 tests are now timing out, here's why:

```
$ .tox/py313/bin/python tests/isolated/patcher_threading_condition.py 
Traceback (most recent call last):
  File "/home/itamarst/devel/eventlet/eventlet/hubs/hub.py", line 471, in fire_timers
    timer()
    ~~~~~^^
  File "/home/itamarst/devel/eventlet/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
    ~~^^^^^^^^^^^^^
  File "/home/itamarst/devel/eventlet/eventlet/semaphore.py", line 147, in _do_acquire    waiter.switch()
    ~~~~~~~~~~~~~^^
greenlet.error: cannot switch to a different thread
```

2024-09-11 17:15 UTC, itamarst commented
As per https://github.com/python-greenlet/greenlet/issues/425, the current approach to just reusing `_thread.start_joinable_thread` from stdlib is completely wrong. Instead, we need to either:

1. Emulate Python 3.13's new `_ThreadHandle` and `start_joinable_thread` APIs, since that's what stdlib `threading.py` is using in 3.13.
2. Copy threading.py implementation from 3.12 and reuse it in 3.13.
3. Not bother supporting 3.13; this depends on whether OpenStack wants this or not.

Just another example of the ways this project is unsustainable, then.

2024-09-11 17:27 UTC, 4383 commented
Thanks for your feedback.

Unfortunatelly, from an openstack point of view, I don't think we will be able to ignore 3.13... I need to discuss that point with the infra team to see when they plan to introduce this python version in our supported runtimes.

Will back soon with details from our agenda.

2024-09-11 17:57 UTC, itamarst commented
That's fine, solving this is totally doable, just wanted to make sure it's worth someone spending time on.

2024-09-12 07:16 UTC, 4383 commented
@itamarst Do this PR looks ok for review/merge, or do you plan to add something more into this branch?

2024-09-12 11:53 UTC, itamarst commented
Given 3.13 is unusable in this branch, the PR should not be merged yet.

2024-09-12 15:17 UTC, 4383 commented
ack, thanks

2024-10-17 11:03 UTC, MeggyCal commented
Hi, I tried your change on the stable Python 3.13 and the tests still throw an error. Hope that helps.

```
[  166s] =================================== FAILURES ===================================
[  166s] ___________________________ test_threading_condition ___________________________
[  166s] 
[  166s] path = '/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/tests/isolated/patcher_threading_condition.py'
[  166s] env = None, args = None, timeout = 10, pythonpath_extend = None
[  166s] expect_pass = True
[  166s] 
[  166s]     def run_python(path, env=None, args=None, timeout=None, pythonpath_extend=None, expect_pass=False):
[  166s]         new_argv = [sys.executable]
[  166s]         new_env = os.environ.copy()
[  166s]         new_env.setdefault('eventlet_test_in_progress', 'yes')
[  166s]         src_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
[  166s]         if path:
[  166s]             path = os.path.abspath(path)
[  166s]             new_argv.append(path)
[  166s]             new_env['PYTHONPATH'] = os.pathsep.join(sys.path + [src_dir])
[  166s]         if env:
[  166s]             new_env.update(env)
[  166s]         if pythonpath_extend:
[  166s]             new_path = [p for p in new_env.get('PYTHONPATH', '').split(os.pathsep) if p]
[  166s]             new_path.extend(
[  166s]                 p if os.path.isabs(p) else os.path.join(src_dir, p) for p in pythonpath_extend
[  166s]             )
[  166s]             new_env['PYTHONPATH'] = os.pathsep.join(new_path)
[  166s]         if args:
[  166s]             new_argv.extend(args)
[  166s]         p = subprocess.Popen(
[  166s]             new_argv,
[  166s]             env=new_env,
[  166s]             stderr=subprocess.STDOUT,
[  166s]             stdin=subprocess.PIPE,
[  166s]             stdout=subprocess.PIPE,
[  166s]         )
[  166s]         if timeout is None:
[  166s]             timeout = 10
[  166s]         try:
[  166s] >           output, _ = p.communicate(timeout=timeout)
[  166s] 
[  166s] tests/__init__.py:338: 
[  166s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  166s] /usr/lib64/python3.13/subprocess.py:1219: in communicate
[  166s]     stdout, stderr = self._communicate(input, endtime, timeout)
[  166s] /usr/lib64/python3.13/subprocess.py:2123: in _communicate
[  166s]     self._check_timeout(endtime, orig_timeout, stdout, stderr)
[  166s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  166s] 
[  166s] self = <Popen: returncode: -9 args: ['/usr/bin/python3.13', '/home/abuild/rpmbuild/...>
[  166s] endtime = 105.174206268, orig_timeout = 10
[  166s] stdout_seq = [b'Traceback (most recent call last):\n', b'  File "/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/eventlet/hubs/hub.py",...\n\tExpected: <greenlet.greenlet object at 0x7fb808ffec80 (otid=0x7fb809020630) suspended active started main>\n', b'']
[  166s] stderr_seq = None, skip_check_and_raise = False
[  166s] 
[  166s]     def _check_timeout(self, endtime, orig_timeout, stdout_seq, stderr_seq,
[  166s]                        skip_check_and_raise=False):
[  166s]         """Convenience for checking if a timeout has expired."""
[  166s]         if endtime is None:
[  166s]             return
[  166s]         if skip_check_and_raise or _time() > endtime:
[  166s] >           raise TimeoutExpired(
[  166s]                     self.args, orig_timeout,
[  166s]                     output=b''.join(stdout_seq) if stdout_seq else None,
[  166s]                     stderr=b''.join(stderr_seq) if stderr_seq else None)
[  166s] E           subprocess.TimeoutExpired: Command '['/usr/bin/python3.13', '/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/tests/isolated/patcher_threading_condition.py']' timed out after 10 seconds
[  166s] 
[  166s] /usr/lib64/python3.13/subprocess.py:1263: TimeoutExpired
[  166s] 
[  166s] During handling of the above exception, another exception occurred:
[  166s] 
[  166s]     def test_threading_condition():
[  166s] >       tests.run_isolated('patcher_threading_condition.py')
[  166s] 
[  166s] tests/patcher_test.py:490: 
[  166s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  166s] tests/__init__.py:365: in run_isolated
[  166s]     run_python(prefix + path, **kwargs)
[  166s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  166s] 
[  166s] path = '/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/tests/isolated/patcher_threading_condition.py'
[  166s] env = None, args = None, timeout = 10, pythonpath_extend = None
[  166s] expect_pass = True
[  166s] 
[  166s]     def run_python(path, env=None, args=None, timeout=None, pythonpath_extend=None, expect_pass=False):
[  166s]         new_argv = [sys.executable]
[  166s]         new_env = os.environ.copy()
[  166s]         new_env.setdefault('eventlet_test_in_progress', 'yes')
[  166s]         src_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
[  166s]         if path:
[  166s]             path = os.path.abspath(path)
[  166s]             new_argv.append(path)
[  166s]             new_env['PYTHONPATH'] = os.pathsep.join(sys.path + [src_dir])
[  166s]         if env:
[  166s]             new_env.update(env)
[  166s]         if pythonpath_extend:
[  166s]             new_path = [p for p in new_env.get('PYTHONPATH', '').split(os.pathsep) if p]
[  166s]             new_path.extend(
[  166s]                 p if os.path.isabs(p) else os.path.join(src_dir, p) for p in pythonpath_extend
[  166s]             )
[  166s]             new_env['PYTHONPATH'] = os.pathsep.join(new_path)
[  166s]         if args:
[  166s]             new_argv.extend(args)
[  166s]         p = subprocess.Popen(
[  166s]             new_argv,
[  166s]             env=new_env,
[  166s]             stderr=subprocess.STDOUT,
[  166s]             stdin=subprocess.PIPE,
[  166s]             stdout=subprocess.PIPE,
[  166s]         )
[  166s]         if timeout is None:
[  166s]             timeout = 10
[  166s]         try:
[  166s]             output, _ = p.communicate(timeout=timeout)
[  166s]         except subprocess.TimeoutExpired:
[  166s]             p.kill()
[  166s]             output, _ = p.communicate(timeout=timeout)
[  166s]             if expect_pass:
[  166s]                 sys.stderr.write('Program {} output:\n---\n{}\n---\n'.format(path, output.decode()))
[  166s] >               assert False, 'timed out'
[  166s] E               AssertionError: timed out
[  166s] 
[  166s] tests/__init__.py:344: AssertionError
[  166s] ----------------------------- Captured stderr call -----------------------------
[  166s] Program /home/abuild/rpmbuild/BUILD/eventlet-0.37.0/tests/isolated/patcher_threading_condition.py output:
[  166s] ---
[  166s] Traceback (most recent call last):
[  166s]   File "/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/eventlet/hubs/hub.py", line 471, in fire_timers
[  166s]     timer()
[  166s]     ~~~~~^^
[  166s]   File "/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/eventlet/hubs/timer.py", line 59, in __call__
[  166s]     cb(*args, **kw)
[  166s]     ~~^^^^^^^^^^^^^
[  166s]   File "/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/eventlet/semaphore.py", line 147, in _do_acquire
[  166s]     waiter.switch()
[  166s]     ~~~~~~~~~~~~~^^
[  166s] greenlet.error: Cannot switch to a different thread
[  166s] 	Current:  <greenlet.greenlet object at 0x7fb8073e4b80 (otid=0x7fb807710ba0) suspended active started main>
[  166s] 	Expected: <greenlet.greenlet object at 0x7fb808ffec80 (otid=0x7fb809020630) suspended active started main>
[  166s] 
[  166s] ---
[  166s] _____________________________ test_threading_join ______________________________
[  166s] 
[  166s] path = '/home/abuild/rpmbuild/BUILD/eventlet-0.37.0/tests/isolated/patcher_threading_join.py'
[  166s] env = None, args = None, timeout = 10, pythonpath_extend = None
[  166s] expect_pass = True
[  166s] 
[  166s]     def run_python(path, en [...]

2024-10-17 13:12 UTC, 4383 commented
Thanks @MeggyCal  all contributions are welcome :)

2024-12-09 18:16 UTC, itamarst commented
A newer version of this got merged. If you are seeing bugs in the released version on 3.13, please open new issues.

2024-12-09 18:16 UTC, closed without merging