Drop support of Python 3.7
eventlet/eventlet pull request #967
Opened 2024-06-10 14:54 UTC by 4383

Python 3.7 is not supported since almost 1 year, Debian Buster LTS is ending on 30th June 2024, and github actions only support versions of Python which are not EOL [3].

For all these reasons, I think we can drop the support of Python 3.7.

[1] https://devguide.python.org/versions/
[2] https://www.debian.org/releases/buster/
[3] https://github.com/actions/python-versions?tab=readme-ov-file#support-policy

2024-06-10 14:54 UTC, 4383 commented
Lets drop it at the end of June

2024-12-16 04:35 UTC, kajinamit requested changes
We can probably even remove Python 3.8 because it already reached its EOL, but we can do it later.

2024-12-16 04:35 UTC, kajinamit commented on .github/workflows/test.yaml
> -          - { py: 3.7, toxenv: py37-epolls, ignore-error: false, os: ubuntu-latest }
L47 needs to be removed, too

2024-12-16 09:07 UTC, 4383 commented on .github/workflows/test.yaml
> -          - { py: 3.7, toxenv: py37-epolls, ignore-error: false, os: ubuntu-latest }
Good catch, done. Thanks

2024-12-16 09:09 UTC, 4383 commented
> We can probably even remove Python 3.8 because it already reached its EOL, but we can do it later.

I'm not against removing python 3.8, maybe with a follow up patch early next year.

2025-01-17 15:58 UTC, itamarst approved these changes

2025-01-17 16:14 UTC, merged